# Generated by Django 3.2.9 on 2021-11-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='users.Job'),
        ),
    ]
