# Generated by Django 3.2.9 on 2021-11-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211112_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='click_recomms',
            field=models.ManyToManyField(blank=True, related_name='get_recomms', to='users.Profile'),
        ),
    ]
