# Generated by Django 3.2.9 on 2021-11-13 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_profile_related_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='related_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='related_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
