# Generated by Django 3.2.9 on 2021-11-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_nm',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
