# Generated by Django 3.2.9 on 2021-11-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='click_recomms',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_recomms', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobs',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.Job'),
        ),
    ]
