# Generated by Django 3.2.9 on 2021-11-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jobs',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='jobs_set', to='users.Job'),
        ),
    ]
