# Generated by Django 3.2.9 on 2021-11-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='click_recomms',
            field=models.ManyToManyField(blank=True, related_name='get_recomms', to='users.Profile'),
        ),
    ]
