# Generated by Django 3.2.9 on 2021-11-22 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('get_staff', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getstaffpost',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='users.Job'),
        ),
        migrations.AddField(
            model_name='getstaffpost',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='commentgetstaff',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_staff.getstaffpost'),
        ),
        migrations.AddField(
            model_name='commentgetstaff',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
