# Generated by Django 3.2.9 on 2021-11-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_g',
            name='content',
            field=models.TextField(default='content'),
        ),
    ]
