# Generated by Django 3.2.9 on 2021-11-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_staff', '0002_post_g_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_g',
            new_name='GetStaffPost',
        ),
    ]
