# Generated by Django 3.2.9 on 2021-11-15 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_jobs'),
        ('get_staff', '0003_rename_post_g_getstaffpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='getstaffpost',
            name='content',
        ),
        migrations.CreateModel(
            name='CommentGetStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 11, 15, 20, 31, 4, 643137), editable=False)),
                ('is_anon', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_staff.getstaffpost')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
