# Generated by Django 3.2.9 on 2021-11-15 20:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_staff', '0004_auto_20211115_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='b',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentgetstaff',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 20, 45, 16, 731026), editable=False),
        ),
    ]
