# Generated by Django 3.2.9 on 2021-11-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_jobs'),
        ('get_staff', '0006_auto_20211115_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterModelOptions(
            name='getstaffpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='getstaffpost',
            name='content',
            field=models.TextField(default='content'),
        ),
        migrations.AddField(
            model_name='getstaffpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='getstaffpost',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='getstaffpost',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='getstaffpost',
            name='hourly_pay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='getstaffpost',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='users.Job'),
        ),
        migrations.AddField(
            model_name='getstaffpost',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='getstaffpost',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='getstaffpost',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='commentgetstaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
